### ISSUE TITLE
Dropwizard 4.x (and 5.x) not compatible with Logback core and classic beyond 1.5.12

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/kiwi-bom#1239]
kiwi-bom 2.0.19 updated logback-classic and logback-core from 1.5.11 to 1.5.15, while the (legacy) logback-access stayed at 1.4.14.

After working through several updates, a bunch of tests started failing in kiwi-test with the following error:

```
java.lang.Exception: java.lang.AbstractMethodError:
Missing implementation of resolved method 'abstract java.util.Map getDefaultConverterSupplierMap()' 
of abstract class ch.qos.logback.core.pattern.PatternLayoutBase.
```

The problem started in logback-core 1.5.13, which introduces the following method in `ch.qos.logback.core.pattern.PatternLayoutBase`:

```java
protected abstract Map<String, Supplier<DynamicConverter>> getDefaultConverterSupplierMap();
```

This method is not implemented by `ch.qos.logback.acces.PatternLayout` in logback-access 1.4.14 (since it is a much earlier version).

Even when you update logback-access to 1.5.13 (or higher), `ch.qos.logback.access.common.PatternLayout` (note the extra 'common' subpackage) still does not implement `getDefaultConverterSupplierMap` and cannot work.

In addition, Dropwizard 4.x (and 5.x alpha versions as of this writing) has the `LogbackAccessRequestLayout` class in dropwizard-request-logging, which extends `ch.qos.logback.access.PatternLayout` (note there is no 'common' package) so it won't work with logback-access 1.5.x anyway.

So, at present until Dropwizard 4.x and 5.x are updated, we cannot go beyond the following versions:

- logback-access 1.4.14
- logback-classic 1.5.12
- logback-core 1.5.12

So, this issue is to revert logback-classic and logback-core to 1.5.12, which is the highest version that still works with logback-access 1.4.14.

**Comment by sleberknight** [comment]
I looked at this again and what basically happened is that logback-core 1.5.13:

* _deprecated_ `getDefaultConverterMap()` in `PatternLayoutBase`
* _added_ the `abstract` method `getDefaultConverterSupplierMap()`

Since  `getDefaultConverterSupplierMap()` is abstract, this _breaks all existing implementations_. Frankly, this should not have been a patch release, since it breaks any code that extends `PatternLayoutBase`. But what do I know?

Anyway, the core problem is that Dropwizard's `LogbackAccessRequestLayout` in dropwizard-request-logging library extends `PatternLayoutBase` and therefore breaks if you attempt to use any existing version (e.g., 4.0.11) with logback-core 1.5.13 or higher.

**Comment by sleberknight** [comment]
I think the other problem is that logback-access was split out into a separate repository, and the artifactId was "relocated" from `ch.qos.logback:logback-access` to `ch.qos.logback.access:common` and the package names also changed from `ch.qos.logback.access` to `ch.qos.logback.access.common`. So, there's clearly a lot going on here and I admit that I don't fully understand what versions are compatible.

The latest `ch.qos.logback.access:common` version is 2.0.3 and it depends on an older version of logback-core, 1.5.7, so it works fine since the `getDefaultConverterSupplierMap()` method was introduced in logback-core 1.5.13.

So, the `PatternLayout` in the relocated logback-access version 2.03 works because it depends on logback-core 1.5.7.  This dependency gets updated to logback-core 1.5.9 in 2.0.4, and to 1.5.14 in 2.0.5, and to 1.5.16 in 2.0.6. And version 2.0.5 is where `PatternLayout` adds an implementation for `getDefaultConverterSupplierMap()`.

But, regardless of all this, Dropwizard is still using the older logback-access, so `LogbackAccessRequestLayout` in dropwizard-request-logging depends on the `PatternLayoutBase` under the _old_ package name, `ch.qos.logback.access.PatternLayout`. As a result, it can _not_ work with the new logback-access 2.0.x versions, since `PatternLayoutBase` is under the _new_ package name, `ch.qos.logback.access.common`.

Ok, so after all this meandering, basically we can't fix anything until _Dropwizard_ updates all its logback dependencies. And Dropwizard 4.0.x and the 5.0.0-alpha-N versions are all still using logback version 1.4.14.

**Comment by sleberknight** [comment]
And perhaps here is the missing piece as to why we are able to use the 1.5.x versions of logback-core and logback-classic:

> The 1.5.x series is a direct descendant of and a drop-in replacement for the 1.4.x series. It differs from the 1.4.x series by the relocation of the logback-access module which was moved to its own separate github repository. 

ref: _On the 1.5.x series_ in https://logback.qos.ch/news.html

But, after the `getDefaultConverterSupplierMap()` method was added in logback-core 1.5.13, I think the statement that "The 1.5.x series is a drop-in replacement for the 1.4.x series" no longer holds. And I think _this_ is why we must wait until Dropwizard updates to logback-core/classic 1.5.x _and_ to the relocated logback-access 2.0.x (and updates `LogbackAccessRequestLayout` i the process).
